//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealership.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Request_Id { get; set; }
        public int Customer_Id { get; set; }
        public int Car_Id { get; set; }
        public int RequestStatus_Id { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
